### ISSUE TITLE
Creating a KWebpage class instance with $template_id null, will result in couch/index.php being added to the database as a template.

### ISSUE THREAD

**Issue by thomaswalker-dev** [CouchCMS/CouchCMS#100]
As the title says, creating a _KWebpage_ instance with _$template_id_ constructor parameter as _null_ will result in _couch/index.php_ being added as a template in _couch_templates_ table.

My guess is that the __fill_template_info_ function in _KWebpage_ is causing this. Specifically this code:
```
if( !count($rs) ){
    // Template needs to be added. Make sure the user is logged-in as super-admin
   $AUTH->check_access( K_ACCESS_LEVEL_SUPER_ADMIN );
   $rs = $DB->insert( K_TBL_TEMPLATES, array('name'=>$tpl_name, 'description'=>'') );
   $rs = $DB->select( K_TBL_TEMPLATES, array('*'), "name='" . $DB->sanitize( $tpl_name ). "'" );
   if( !count($rs) ) die( "ERROR: Failed to insert record in K_TBL_TEMPLATES" );

   // HOOK: template_inserted
   $FUNCS->dispatch_event( 'template_inserted', array(&$rs[0], &$this) );
}
```
I'm not sure this is a bug or it's an intended feature.

**Comment by kksidd** [comment]
I'd say that is the expected behavior - Couch expects the constructor to be called with either the template's id or its name. If both are absent, it assumes that the call was made from within a template and proceeds accordingly (e.g. register the template if required).

The core code takes care this assumption is not broken (empty constructor is called only from frontend templates). Any custom code would be expected to do the same.
