### ISSUE TITLE
Option to toggle HTTP response code 301

### ISSUE THREAD

**Issue by Ketrel** [CouchCMS/CouchCMS#17]
Could sending the HTTP response code 301 with the redirects for PrettyURLs be an option able which can be toggled via the config rather than hard coded?

When they're enabled, the redirect itself gets cached will persist if turned off until one clears their browser cache.

It'd be nicer to be able to toggle them off when desired rather than having to edit that part out of the code.

**Comment by cheesypoof** [comment]
The expectation is that one would not normally disable Pretty URLs after having it enabled for any significant period of time (in a production environment).

Nevertheless, you could find and replace `301` with `302` in the generated .htaccess file to make the redirects "temporary" and thus prevent the aforementioned caching.

**Comment by Ketrel** [comment]
That's not the scenario in which it causes issues

If I go to site.com/file.php with pretty URLS on it directs me to site.com/file/

If I turn them off, that redirect gets cached and I can't hit file.php because the browser will just keep doing the redirect.

This isn't the .htaccess that's the problem.

**Comment by Ketrel** [comment]
I submitted a pull request which adds an option to change the code (defaults to 301 as it is now)

**Comment by cheesypoof** [comment]
@Ketrel, the scenario you described is exactly what I had in mind. You are nevertheless correct that this isn't handled entirely by the generated .htaccess file, but also fixed core code (like that modified in your PR - #18).

The use of `301`, as opposed to `302`, has very meaningful implications for things like search engine bots, which is why the current values are deliberate. Additionally, `301` requests need not be cached by a browser if one opts to specify appropriate `Cache-Control` and/or `Expires` headers.

In my opinion, the current implementation is not broken or lacking, and does not accordingly necessitate options for customization.

If you have any questions about whether a pull request is likely to be merged, please feel free to message us on the forums. Thanks for taking the time to contribute to Couch.
